theme: minima
minima:
  skin: dark
title: My Portfolio
author: Tom Jago
email: tom.jago@hotmail.com
description: A portfolio showcasing my work and projects.
excerpt_separator: <!-- excerpt-end -->
timezone: Europe/London
